### ISSUE TITLE
Editor: Only HTTPS URLs

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/integreat-cms#387] opened 2020-05-06 07:16 UTC
iOS and Android only support HTTPS URLs. This means we need to ensure no HTTP URLs are set in the editor. If a user enters a HTTP URL, we should check if the resource is available with HTTPS. If yes, the link could be updated automatically. If the resource is not available, the user should be warned and the link rejected.

**Comment by timoludwig** [comment] 2021-04-14 14:13
Duplicate of #68

**Closed by timoludwig** 2021-04-14 14:13 UTC
Labels: prio: low
