### ISSUE TITLE
Automatically create Matomo instances for new regions

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/integreat-cms#798] opened 2021-04-29 17:49 UTC
### Motivation

Creating new Matomo instances for new regions is still a manual process and could be automated.

### Proposed Solution

When a new region is created in the CMS, the Matomo API can be used to automatically create a new corresponding Matomo instance.

**Comment by ulliholtgrave** [comment] 2021-05-12 11:07
Duplicate of #107

**Closed by ulliholtgrave** 2021-05-12 11:07 UTC
Labels: feature, prio: low
